# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_pivots_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import chrome_search_api_request_context_pb2 as chrome__search__api__request__context__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='get_pivots_request.proto',
  package='contextual_suggestions',
  syntax='proto2',
  serialized_pb=_b('\n\x18get_pivots_request.proto\x12\x16\x63ontextual_suggestions\x1a\'chrome_search_api_request_context.proto\"\x8b\x01\n\x10GetPivotsRequest\x12@\n\x07\x63ontext\x18\x01 \x01(\x0b\x32/.contextual_suggestions.SearchApiRequestContext\x12\x35\n\x05query\x18\x02 \x01(\x0b\x32&.contextual_suggestions.GetPivotsQuery\"\xa0\x02\n\x0eGetPivotsQuery\x12\x37\n\x07\x63ontext\x18\x01 \x03(\x0b\x32&.contextual_suggestions.ExploreContext\x12\x44\n\x0f\x64ocument_params\x18\x02 \x01(\x0b\x32+.contextual_suggestions.PivotDocumentParams\x12H\n\x11\x63lustering_params\x18\x06 \x01(\x0b\x32-.contextual_suggestions.PivotClusteringParams\x12\x45\n\x10peek_text_params\x18\x07 \x01(\x0b\x32+.contextual_suggestions.PivotPeekTextParams\"\x1d\n\x0e\x45xploreContext\x12\x0b\n\x03url\x18\x01 \x01(\t\"\xa7\x02\n\x13PivotDocumentParams\x12\x16\n\x07\x65nabled\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x0e\n\x03num\x18\x02 \x01(\x05:\x01\x35\x12\x18\n\rmin_documents\x18\x06 \x01(\x05:\x01\x33\x12\x1c\n\renable_images\x18\x03 \x01(\x08:\x05\x66\x61lse\x12r\n\x12image_aspect_ratio\x18\x04 \x01(\x0e\x32<.contextual_suggestions.PivotDocumentParams.ImageAspectRatio:\x18\x41SPECT_RATIO_UNSPECIFIED\"<\n\x10ImageAspectRatio\x12\x1c\n\x18\x41SPECT_RATIO_UNSPECIFIED\x10\x00\x12\n\n\x06SQUARE\x10\x01\"B\n\x15PivotClusteringParams\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x12\x0b\n\x03min\x18\x02 \x01(\x05\x12\x0b\n\x03max\x18\x03 \x01(\x05\"-\n\x13PivotPeekTextParams\x12\x16\n\x07\x65nabled\x18\x01 \x01(\x08:\x05\x66\x61lseB\x02H\x03')
  ,
  dependencies=[chrome__search__api__request__context__pb2.DESCRIPTOR,])



_PIVOTDOCUMENTPARAMS_IMAGEASPECTRATIO = _descriptor.EnumDescriptor(
  name='ImageAspectRatio',
  full_name='contextual_suggestions.PivotDocumentParams.ImageAspectRatio',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ASPECT_RATIO_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQUARE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=793,
  serialized_end=853,
)
_sym_db.RegisterEnumDescriptor(_PIVOTDOCUMENTPARAMS_IMAGEASPECTRATIO)


_GETPIVOTSREQUEST = _descriptor.Descriptor(
  name='GetPivotsRequest',
  full_name='contextual_suggestions.GetPivotsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='contextual_suggestions.GetPivotsRequest.context', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='query', full_name='contextual_suggestions.GetPivotsRequest.query', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=233,
)


_GETPIVOTSQUERY = _descriptor.Descriptor(
  name='GetPivotsQuery',
  full_name='contextual_suggestions.GetPivotsQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context', full_name='contextual_suggestions.GetPivotsQuery.context', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='document_params', full_name='contextual_suggestions.GetPivotsQuery.document_params', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clustering_params', full_name='contextual_suggestions.GetPivotsQuery.clustering_params', index=2,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peek_text_params', full_name='contextual_suggestions.GetPivotsQuery.peek_text_params', index=3,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=524,
)


_EXPLORECONTEXT = _descriptor.Descriptor(
  name='ExploreContext',
  full_name='contextual_suggestions.ExploreContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='contextual_suggestions.ExploreContext.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=555,
)


_PIVOTDOCUMENTPARAMS = _descriptor.Descriptor(
  name='PivotDocumentParams',
  full_name='contextual_suggestions.PivotDocumentParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='contextual_suggestions.PivotDocumentParams.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='contextual_suggestions.PivotDocumentParams.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_documents', full_name='contextual_suggestions.PivotDocumentParams.min_documents', index=2,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_images', full_name='contextual_suggestions.PivotDocumentParams.enable_images', index=3,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_aspect_ratio', full_name='contextual_suggestions.PivotDocumentParams.image_aspect_ratio', index=4,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PIVOTDOCUMENTPARAMS_IMAGEASPECTRATIO,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=853,
)


_PIVOTCLUSTERINGPARAMS = _descriptor.Descriptor(
  name='PivotClusteringParams',
  full_name='contextual_suggestions.PivotClusteringParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='contextual_suggestions.PivotClusteringParams.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min', full_name='contextual_suggestions.PivotClusteringParams.min', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max', full_name='contextual_suggestions.PivotClusteringParams.max', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=855,
  serialized_end=921,
)


_PIVOTPEEKTEXTPARAMS = _descriptor.Descriptor(
  name='PivotPeekTextParams',
  full_name='contextual_suggestions.PivotPeekTextParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enabled', full_name='contextual_suggestions.PivotPeekTextParams.enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=923,
  serialized_end=968,
)

_GETPIVOTSREQUEST.fields_by_name['context'].message_type = chrome__search__api__request__context__pb2._SEARCHAPIREQUESTCONTEXT
_GETPIVOTSREQUEST.fields_by_name['query'].message_type = _GETPIVOTSQUERY
_GETPIVOTSQUERY.fields_by_name['context'].message_type = _EXPLORECONTEXT
_GETPIVOTSQUERY.fields_by_name['document_params'].message_type = _PIVOTDOCUMENTPARAMS
_GETPIVOTSQUERY.fields_by_name['clustering_params'].message_type = _PIVOTCLUSTERINGPARAMS
_GETPIVOTSQUERY.fields_by_name['peek_text_params'].message_type = _PIVOTPEEKTEXTPARAMS
_PIVOTDOCUMENTPARAMS.fields_by_name['image_aspect_ratio'].enum_type = _PIVOTDOCUMENTPARAMS_IMAGEASPECTRATIO
_PIVOTDOCUMENTPARAMS_IMAGEASPECTRATIO.containing_type = _PIVOTDOCUMENTPARAMS
DESCRIPTOR.message_types_by_name['GetPivotsRequest'] = _GETPIVOTSREQUEST
DESCRIPTOR.message_types_by_name['GetPivotsQuery'] = _GETPIVOTSQUERY
DESCRIPTOR.message_types_by_name['ExploreContext'] = _EXPLORECONTEXT
DESCRIPTOR.message_types_by_name['PivotDocumentParams'] = _PIVOTDOCUMENTPARAMS
DESCRIPTOR.message_types_by_name['PivotClusteringParams'] = _PIVOTCLUSTERINGPARAMS
DESCRIPTOR.message_types_by_name['PivotPeekTextParams'] = _PIVOTPEEKTEXTPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetPivotsRequest = _reflection.GeneratedProtocolMessageType('GetPivotsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPIVOTSREQUEST,
  __module__ = 'get_pivots_request_pb2'
  # @@protoc_insertion_point(class_scope:contextual_suggestions.GetPivotsRequest)
  ))
_sym_db.RegisterMessage(GetPivotsRequest)

GetPivotsQuery = _reflection.GeneratedProtocolMessageType('GetPivotsQuery', (_message.Message,), dict(
  DESCRIPTOR = _GETPIVOTSQUERY,
  __module__ = 'get_pivots_request_pb2'
  # @@protoc_insertion_point(class_scope:contextual_suggestions.GetPivotsQuery)
  ))
_sym_db.RegisterMessage(GetPivotsQuery)

ExploreContext = _reflection.GeneratedProtocolMessageType('ExploreContext', (_message.Message,), dict(
  DESCRIPTOR = _EXPLORECONTEXT,
  __module__ = 'get_pivots_request_pb2'
  # @@protoc_insertion_point(class_scope:contextual_suggestions.ExploreContext)
  ))
_sym_db.RegisterMessage(ExploreContext)

PivotDocumentParams = _reflection.GeneratedProtocolMessageType('PivotDocumentParams', (_message.Message,), dict(
  DESCRIPTOR = _PIVOTDOCUMENTPARAMS,
  __module__ = 'get_pivots_request_pb2'
  # @@protoc_insertion_point(class_scope:contextual_suggestions.PivotDocumentParams)
  ))
_sym_db.RegisterMessage(PivotDocumentParams)

PivotClusteringParams = _reflection.GeneratedProtocolMessageType('PivotClusteringParams', (_message.Message,), dict(
  DESCRIPTOR = _PIVOTCLUSTERINGPARAMS,
  __module__ = 'get_pivots_request_pb2'
  # @@protoc_insertion_point(class_scope:contextual_suggestions.PivotClusteringParams)
  ))
_sym_db.RegisterMessage(PivotClusteringParams)

PivotPeekTextParams = _reflection.GeneratedProtocolMessageType('PivotPeekTextParams', (_message.Message,), dict(
  DESCRIPTOR = _PIVOTPEEKTEXTPARAMS,
  __module__ = 'get_pivots_request_pb2'
  # @@protoc_insertion_point(class_scope:contextual_suggestions.PivotPeekTextParams)
  ))
_sym_db.RegisterMessage(PivotPeekTextParams)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
