# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_decode_stats.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_decode_stats.proto',
  package='media',
  syntax='proto2',
  serialized_pb=_b('\n\x18video_decode_stats.proto\x12\x05media\"m\n\x10\x44\x65\x63odeStatsProto\x12\x16\n\x0e\x66rames_decoded\x18\x01 \x01(\x04\x12\x16\n\x0e\x66rames_dropped\x18\x02 \x01(\x04\x12)\n\x1e\x66rames_decoded_power_efficient\x18\x03 \x01(\x04:\x01\x30\x42\x02H\x03')
)




_DECODESTATSPROTO = _descriptor.Descriptor(
  name='DecodeStatsProto',
  full_name='media.DecodeStatsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames_decoded', full_name='media.DecodeStatsProto.frames_decoded', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frames_dropped', full_name='media.DecodeStatsProto.frames_dropped', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frames_decoded_power_efficient', full_name='media.DecodeStatsProto.frames_decoded_power_efficient', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['DecodeStatsProto'] = _DECODESTATSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DecodeStatsProto = _reflection.GeneratedProtocolMessageType('DecodeStatsProto', (_message.Message,), dict(
  DESCRIPTOR = _DECODESTATSPROTO,
  __module__ = 'video_decode_stats_pb2'
  # @@protoc_insertion_point(class_scope:media.DecodeStatsProto)
  ))
_sym_db.RegisterMessage(DecodeStatsProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
